[build]
	command = "pnpm run build"
	publish = "dist"

# [functions]
# 	external_node_modules = ["astro"]

# [functions]
# external_node_modules=["sharp"]
# included_files = ["node_modules/sharp/**/*"]
